### ISSUE TITLE
fail to build on ubuntu

### ISSUE THREAD

**Issue by chakpongchung** [swlaschin/DomainModelingMadeFunctional#11]
```
cpchung:DomainModelingMadeFunctional$ ./build.sh 
Paket version 5.238.1
The last restore is still up to date. Nothing left to do.
Performance:
 - Runtime: 81 milliseconds
Building project with version: LocalBuild
Shortened DependencyGraph for Target Build:
<== Build
   <== Restore
      <== InstallDotNetCLI
         <== Clean

The running order is:
  - Clean
  - InstallDotNetCLI
  - Restore
  - Build
Running build with 1 worker
Starting Target: Clean 
Deleting contents of ./build/
Finished Target: Clean
Starting Target: InstallDotNetCLI (==> Clean)
dotnet --info
﻿/home/cpchung/.local/share/dotnetcore/dotnet --info
﻿cmd 2.1.4 already installed in LocalApplicationData
Finished Target: InstallDotNetCLI
Starting Target: Restore (==> InstallDotNetCLI)
/home/cpchung/.local/share/dotnetcore/dotnet restore
﻿MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.InvalidOperationException: The terminfo database is invalid.
   at System.TermInfo.Database..ctor(String term, Byte[] data)
   at System.TermInfo.Database.ReadDatabase(String term, String directoryPath)
   at System.TermInfo.Database.ReadDatabase(String term)
   at System.TermInfo.Database.ReadActiveDatabase()
   at System.ConsolePal.TerminalFormatStrings.<>c.<.cctor>b__27_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.ConsolePal.EnsureInitializedCore()
   at System.ConsolePal.ControlCHandlerRegistrar.Register()
   at System.Console.add_CancelKeyPress(ConsoleCancelEventHandler value)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine) in E:\A\_work\17\s\src\MSBuild\XMake.cs:line 526

Unhandled Exception: System.InvalidOperationException: The terminfo database is invalid.
   at System.TermInfo.Database..ctor(String term, Byte[] data)
   at System.TermInfo.Database.ReadDatabase(String term, String directoryPath)
   at System.TermInfo.Database.ReadDatabase(String term)
   at System.TermInfo.Database.ReadActiveDatabase()
   at System.ConsolePal.TerminalFormatStrings.<>c.<.cctor>b__27_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.ConsolePal.EnsureInitializedCore()
   at System.ConsolePal.ControlCHandlerRegistrar.Register()
   at System.Console.add_CancelKeyPress(ConsoleCancelEventHandler value)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine) in E:\A\_work\17\s\src\MSBuild\XMake.cs:line 748
   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args) in E:\A\_work\17\s\src\MSBuild\XMake.cs:line 215
Running build failed.
Error:
System.Exception: dotnet restore failed
  at Microsoft.FSharp.Core.PrintfModule+PrintFormatToStringThenFail@1379[TResult].Invoke (System.String message) [0x00001] in <5893d081904cf4daa745038381d09358>:0 
  at FSI_0005.Build.runDotnet (System.String workingDir, System.String args) [0x00043] in <4a3ea9301b374a8aa6ab1c1f125b528d>:0 
  at FSI_0005.Build+clo@56-4.Invoke (System.String p) [0x0000a] in <4a3ea9301b374a8aa6ab1c1f125b528d>:0 
  at Microsoft.FSharp.Collections.SeqModule.Iterate[T] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] action, System.Collections.Generic.IEnumerable`1[T] source) [0x0002d] in <5893d081904cf4daa745038381d09358>:0 
  at FSI_0005.Build+clo@54-3.Invoke (Microsoft.FSharp.Core.Unit _arg3) [0x0000b] in <4a3ea9301b374a8aa6ab1c1f125b528d>:0 
  at Fake.TargetHelper.runSingleTarget (Fake.TargetHelper+TargetTemplate`1[a] target) [0x00049] in <5aa25359ccf1c534a74503835953a25a>:0 

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target             Duration
------             --------
Clean              00:00:00.0014879
InstallDotNetCLI   00:00:00.1250078
Restore            Failure
Total:             00:00:00.5667757
---------------------------------------------------------------------
Status:            Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) System.Exception: dotnet restore failed
  at Microsoft.FSharp.Core.PrintfModule+PrintFormatToStringThenFail@1379[TResult].Invoke (System.String message) [0x00001] in <5893d081904cf4daa745038381d09358>:0 
  at FSI_0005.Build.runDotnet (System.String workingDir, System.String args) [0x00043] in <4a3ea9301b374a8aa6ab1c1f125b528d>:0 
  at FSI_0005.Build+clo@56-4.Invoke (System.String p) [0x0000a] in <4a3ea9301b374a8aa6ab1c1f125b528d>:0 
  at Microsoft.FSharp.Collections.SeqModule.Iterate[T] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] action, System.Collections.Generic.IEnumerable`1[T] source) [0x0002d] in <5893d081904cf4daa745038381d09358>:0 
  at FSI_0005.Build+clo@54-3.Invoke (Microsoft.FSharp.Core.Unit _arg3) [0x0000b] in <4a3ea9301b374a8aa6ab1c1f125b528d>:0 
  at Fake.TargetHelper.runSingleTarget (Fake.TargetHelper+TargetTemplate`1[a] target) [0x00049] in <5aa25359ccf1c534a74503835953a25a>:0 
```

```


cpchung:DomainModelingMadeFunctional$ dotnet --info
A compatible installed .NET Core SDK for global.json version [2.1.4] from [/home/cpchung/code/DomainModelingMadeFunctional/global.json] was not found
Install the [2.1.4] .NET Core SDK or update [/home/cpchung/code/DomainModelingMadeFunctional/global.json] with an installed .NET Core SDK:
  3.0.101 [/usr/share/dotnet/sdk]

Host (useful for support):
  Version: 3.0.1
  Commit:  19942e7199

.NET Core SDKs installed:
  3.0.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by chakpongchung** [comment]
is there anyway to automatically adjust the .netcore version according to the installed version?

**Comment by swlaschin** [comment]
I've updated to use .NET 5 which should work fine now
